### ISSUE TITLE
Add integration guide

### ISSUE THREAD

**Issue by martinpengellyphillips** [atoha/dbootstrap#14]
Add a brief guide on integrating the theme with an existing Dojo project.

**Comment by Mennodebrie** [comment]
This would be very helpful, I really like Bootstrap and some pointers on how to use this theme in our Dojo project would be greatly appreciated.

**Comment by martinpengellyphillips** [comment]
Cool - I'll tackle this next.

**Comment by martinpengellyphillips** [comment]
Please take a look at https://github.com/thesociable/dbootstrap/pull/26 and let me know if it helps before I merge.
