### ISSUE TITLE
Padding on text Input Widgets affecting border in webkit browsers

### ISSUE THREAD

**Issue by ghost** [atoha/dbootstrap#15]
The widgets are styled with the following:
  .bootstrap .dijitInputContainer { padding: 6px 6px; }

This is causing the bottom border to shift down which leaves a space at the bottom of the widget trigger. This was tested and verify on the Mac with the following browsers: Chrome (latest) and Safari 5.1.7.

This looked fine with Firefox and Opera 12.

**Comment by martinpengellyphillips** [comment]
Thanks for the report. I'll take a look at how to fix this.

**Comment by martinpengellyphillips** [comment]
Hmmm, this is proving tricky. I might have to rethink how those widgets css are implemented. Any pointers from anyone appreciated.

**Comment by martinpengellyphillips** [comment]
Fixed in #24.
