### ISSUE TITLE
bad path in Gallery.html

### ISSUE THREAD

**Issue by SteveEisner** [atoha/dbootstrap#21]
Thanks so much for your work on this theme. I've just installed it and am playing around & hope to give it some use!

Meanwhile, here's a really small issue:  in your dbootstrap/Gallery.html, references to themes/claro/document.css should be "dijit/themes/claro/document.css" rather than a relative path "../themes/claro/document.css"

This supports those of us who have dojo/dijit/etc off in another directory, aliased by paths in the config.  (for that matter, the current path is broken even for your standard build on http://thesociable.github.com/dbootstrap/)

**Comment by SteveEisner** [comment]
Actually, I guess this isn't exactly true.  Looks like stylesheets aren't being loaded through a path-aware require... they're just standard relative paths. I'm not sure if there's a path-invariant way to fix this in the Gallery.html!

**Comment by martinpengellyphillips** [comment]
Yeah, this looks like a copy and paste error (I took a lot of the template code directly from the official theme tester). Most likely I can remove that css request altogether. 

Thanks for spotting it!

**Comment by martinpengellyphillips** [comment]
I've removed the bad paths. Let me know if you find any others not working.
