### ISSUE TITLE
Trying to build (linux)

### ISSUE THREAD

**Issue by eiswind** [atoha/dbootstrap#39]
Hi, I am a usual backend coder, so I'm not so firm with all the fancy tools you are using. I installed node and stylus on my linux machine, but somehow it does not build
WARNING:dbootstrap.build.execute:Command stylus --include /home/thomas/projects/dbootstrap/source/nib/lib --include /home/thomas/projects/dbootstrap/source/dbootstrap/theme/dbootstrap /home/thomas/projects/dbootstrap/source/dbootstrap/theme/dbootstrap/index.styl exited with code 1

and I #fail to make stylus tell me more about the problem. now I would be very happy if you could help me progress into the "frontend arena" and give me a hint whats going on there,

thx thomas

**Comment by martinpengellyphillips** [comment]
Hey. Sorry to hear you are having trouble building the project. Can you try running the referenced command manually in the terminal and reply with the full output (if any)?

`stylus --include /home/thomas/projects/dbootstrap/source/nib/lib --include /home/thomas/projects/dbootstrap/source/dbootstrap/theme/dbootstrap /home/thomas/projects/dbootstrap/source/dbootstrap/theme/dbootstrap/index.styl`

Also, were you trying to build the demo or the theme?

**Comment by eiswind** [comment]
Hey Martin, after some more investigation, I realized that something was broken with my node installation (I used ubuntu packages). After building node from source everything is fine.

Thanks! Now I'll try to integrate your theme with my prototype ...

**Comment by martinpengellyphillips** [comment]
Ok, thanks for the followup - it's probably worth me adding a prerequisites section to the readme mentioning minimum versions to use.
