### ISSUE TITLE
main.js is trying to load ../when.js

### ISSUE THREAD

**Issue by eiswind** [atoha/dbootstrap#40]
Thanks for pointing me out with my build problem. So here I go again. I still fail to make it work. It's building now, but I see that in main.js it tries to load ../when.js, which unfortunately fails. I found that the reference seem to come somewhere from dojo code, cause I did not see such refs in your code. Did you see something like that or is there just another bad error on my side with th build?

**Comment by martinpengellyphillips** [comment]
Hmmm. I'm not seeing that my side. Can you send the commands you are issuing and the output so I can try to reproduce here?
