### ISSUE TITLE
dojo 1.9 compatibility

### ISSUE THREAD

**Issue by allencblee** [atoha/dbootstrap#47]
Just tried to build with dojo 1.9.0.   The build was successful but when running the demo, it shows an error of "unload to load dojo/selector/lite.js".

**Comment by martinpengellyphillips** [comment]
Confirmed. 

Also, tried using the `--no-prune` option when building. This avoids the missing files error, but the result is still a blank page. Needs further investigation to find out why the application is not loading in Dojo 1.9.

**Comment by allencblee1** [comment]
I didn't use --no-prune.  I got it working by manually copying the selector folder from dojo release into the dojo folder under demo.

**Comment by allencblee1** [comment]
I just rebuild it using --no-prune.  It works.  By the way, I've included the icon_support fix.  Without it, it won't work because it would throw an exception inside the _attachTemplateNodes procedure because of the missing getAttrFunc parameter.

**Comment by martinpengellyphillips** [comment]
Going to update to Dojo 1.9. Will try to maintain backwards compatibility with Dojo 1.8.

**Comment by martinpengellyphillips** [comment]
Updated to Dojo 1.9 and added missing selector/lite.js to demo build.
