### ISSUE TITLE
dijit/TitlePane styling is completely missing

### ISSUE THREAD

**Issue by DavidSpriggs** [atoha/dbootstrap#52]
dijit/TitlePane should have styling rather than blank.

Compare (click the various dijits tab):
http://download.dojotoolkit.org/release-1.8.4/dojo-release-1.8.4/dijit/themes/themeTester.html
vs
http://thesociable.github.io/dbootstrap/

**Comment by martinpengellyphillips** [comment]
Good spot! Any thoughts on what 'look' would be appropriate for the titlepane?

**Comment by DavidSpriggs** [comment]
I would say something similar to the AccordionContainer/AccordionPane.

**Comment by martinpengellyphillips** [comment]
Cool. I'll take a look at getting this done over the weekend.

**Comment by KateHodge** [comment]
@thesociable you created a prebuilt download in response to this question on StackOverflow (http://stackoverflow.com/questions/14815346/dojo-twitter-bootstrap-and-dijits).  However, I think it was before you added the TitlePane css as I'm getting the issue reported above.  I haven't managed to build the project myself so wondered if you could create an updated prebuilt version to download?

**Comment by martinpengellyphillips** [comment]
Try the new one at https://github.com/thesociable/dbootstrap/releases/download/0.1.0/dbootstrap-0.1.0-dojo-1.9.1.zip and let me know how you get on.
