### ISSUE TITLE
Disabled DateTextBox should show date

### ISSUE THREAD

**Issue by gavinr** [atoha/dbootstrap#56]
It is standard for a disabled DateTextBox to show the value even though it can't be changed. Using the DBootstrap theme, however, hides the date on a DateTextBox if it is disabled.

See this Example of the normal (Claro) way and the Dbootstrap version:
http://jsfiddle.net/gavinr/U3Emw/

**Comment by martinpengellyphillips** [comment]
Thanks for the report. I am seeing the displayed value (or placeholder) for disabled date text box (including in your jsfiddle demo) so it is probably a browser/OS specific issue. Can you let me know which browser and OS you are using?

**Comment by gavinr** [comment]
Thanks for checking in to it!

Chrome 26.0.1410.64 on Windows 7

![dbootstrap](https://f.cloud.github.com/assets/209355/499571/453229e6-bc4b-11e2-8765-1c30fcfba535.png)

**Comment by martinpengellyphillips** [comment]
I don't have a Win7 machine (though will see if the same issue occurs on Win8). Any chance you could dig into this?

**Comment by gavinr** [comment]
Sure.

**Comment by martinpengellyphillips** [comment]
Confirmed with Chrome on Win8 (and I suspect all webkit based browsers on various OS's). It is a styling issue where the disabled text is ending up the same colour as the background. Will take a look at the styling and precedence to fix.

**Comment by martinpengellyphillips** [comment]
This should now be fixed on master. Can you pull latest and check it has resolved the issue for you?
