### ISSUE TITLE
Update notice about testing and compatibility

### ISSUE THREAD

**Issue by martinpengellyphillips** [atoha/dbootstrap#63]
Currently the demo makes a statement about only being tested against Firefox on Mac which is now out of date. Update the statement to reflect the current testing and compatibility state.

**Comment by martinpengellyphillips** [comment]
Perhaps also setup more comprehensive testing using Sauce Labs.

**Comment by dylans** [comment]
We'd be happy to show you how to set things up with the intern if that's useful!

**Comment by martinpengellyphillips** [comment]
Definitely!
