### ISSUE TITLE
Select dropdowns don't render properly when integrated into default bootstrap theme.

### ISSUE THREAD

**Issue by jaetea** [atoha/dbootstrap#64]
In tables.less in bootstrap there is a default table style that sets border-collapse to collapse.

table {
  max-width: 100%;
  background-color: @tableBackground;
  border-collapse: collapse;
  border-spacing: 0;
}

**Comment by martinpengellyphillips** [comment]
Hi. Not sure I understand what you mean. Can you include a screenshot and details of the browser and OS you are using?

**Comment by IanConnolly** [comment]
I think it might be something along these lines? I'm experiencing this myself (dojo/dijit 1.8.5) 

![screen shot 2013-07-03 at 11 16 19](https://f.cloud.github.com/assets/1179074/742418/a1e94778-e3c9-11e2-88d5-774801207724.png)

Dbootstrap is the only CSS in that page, though the problem also occurs when the Twitter Bootstrap CSS is loaded too.

``` html
<body class="dbootstrap">
    <div data-dojo-type="dijit/form/Form" id="myForm" data-dojo-id="myForm" encType="multipart/form-data" action="" method="">
        <label for="title">Title</label>

        <select name="select1" data-dojo-type="dijit/form/Select">
            <option selected="selected" value="Manager">Manager</option>
            <option value="Employee">Employee</option>
        </select>
</div>

    <script type="text/javascript">
        require(["myapp/test", "dojo/domReady!"], function(test) {
            test.run();
        });
    </script>
</body>
```

``` javascript
define(["dojo/_base/config",
        "dojo/_base/declare",
        "dijit/form/Form",
        "dijit/form/Select",
        "dbootstrap",
        "dojo/parser"],
        function(config, declare, Form, Select, dbootstrap, parser) {

            return {
                run: function() {
                    parser.parse();
                }
            };
        });

```

**Comment by IanConnolly** [comment]
Don't know if you've seen this ye @thesociable, any ideas?

**Comment by martinpengellyphillips** [comment]
Hey. Haven't had time recently to look into this. Will likely get some time in the next few weeks. 

Can you confirm that the behaviour is as expected for you on the demo site (http://thesociable.github.io/dbootstrap/)?

**Comment by IanConnolly** [comment]
Yep, the demo seems to be working fine. I could try the exact version of Dojo and hash of dbootstrap that you're running there if you have them handy?

**Comment by jaetea** [comment]
Inside of select.less I had to add the following to overwrite the bootstrap styling.

.dbootstrap .dijitSelect {
    border: none;
    color: @gray;
    border-collapse: separate;  // Fix for bootstrap table reset.
    transition: border linear .2s, box-shadow linear .2s;
}

**Comment by IanConnolly** [comment]
Sadly, that doesn't seem to have fixed anything here on my end.

**Comment by martinpengellyphillips** [comment]
@jaetea Sounds like you are experiencing a different issue. Could you send a screenshot of the issue you were facing. Also, dbootstrap doesn't use less files so I am curious as to what your setup is?

@NSNO Will look into your example code to figure out a solution.

**Comment by martinpengellyphillips** [comment]
@NSNO Just ran your test against a build of the theme from latest master. It works correctly if you shift dbootstrap to be the first requirement in the list. This is important as dbootstrap monkey-patches some of Dijit to allow font-based icons to work (as per the README, but perhaps I need to **bold** that bit). 

Change

``` javascript
define(["dojo/_base/config",
        "dojo/_base/declare",
        "dijit/form/Form",
        "dijit/form/Select",
        "dbootstrap",
        "dojo/parser"],
        function(config, declare, Form, Select, dbootstrap, parser) {
```

to

``` javascript
define(["dbootstrap",
        "dojo/_base/config",
        "dojo/_base/declare",
        "dijit/form/Form",
        "dijit/form/Select",
        "dojo/parser"],
        function(dbootstrap, config, declare, Form, Select, parser) {
```

and you should get
![dbootstrap_select_dropdown](https://f.cloud.github.com/assets/214338/857278/c399e81a-f54d-11e2-8dc5-18977d33a9d2.png)

**Comment by jaetea** [comment]
I converted the .stylus to .less files so I could leverage the mixins from bootstrap and have to only use one css pre-processer and be able to use the same variables file.

**Comment by martinpengellyphillips** [comment]
@jaetea Ok. I'm still not clear on what the issue was. If you could provide a screenshot that would be great. Otherwise will close this ticket now.

**Comment by jaetea** [comment]
Just close. As I'm moving to 3 RC1 and haven't been able to replicate the issue again.
