### ISSUE TITLE
Download/Build Problem: Commits referenced in Dojo/* repos no longer exist

### ISSUE THREAD

**Issue by IanConnolly** [atoha/dbootstrap#66]
$ git clone --recursive git://github.com/thesociable/dbootstrap.git 

Unable to checkout '961d2ff20aae8432acd1df2fc5f96fbb1b51b71e' in submodule path 'source/dijit'
Unable to checkout '6751624b5bdb4844bcff086be2cc31b557b2fb85' in submodule path 'source/dojo'
Unable to checkout 'b1efee8930384b057c1295f5b28cddb11fbf75c4' in submodule path 'source/dojox'
Unable to checkout '57bdb06edefddf1fcbc0d4a072c5c5b96b9f2950' in submodule path 'source/util'

**Comment by dekristo** [comment]
Seems to work when you do a git checkout on each submodules.

**Comment by DomDerrien** [comment]
Same issue, solved by cloning each folder individually.

**Comment by martinpengellyphillips** [comment]
Confirmed am seeing this as well. Not sure what has changed, perhaps I need to reset the submodules.

**Comment by dylans** [comment]
We moved Dojo from svn to GitHub, so we had to do some repo shuffling with the old github repos (which were simply mirrors of svn). See http://dojotoolkit.org/blog/dojo-is-now-hosted-on-github for some basic details.

**Comment by martinpengellyphillips** [comment]
Ah - thanks Dylan. Will update the references to point to the new repos.

**Comment by martinpengellyphillips** [comment]
This should now be fixed. Thanks again for the report!
