### ISSUE TITLE
Style Tree

### ISSUE THREAD

**Issue by martinpengellyphillips** [atoha/dbootstrap#7]
Need to set the tree icons (dijitFolderClosed, dijitFolderOpened etc) and hover/select colours.

**Comment by martinpengellyphillips** [comment]
Want to change the store to also show a leaf level icon for leaves.

**Comment by hdd** [comment]
Hi Martin, I love this theme, and it seems working well, but it would be nice to have a default icon for the tree leaves, in the claro are represented by a file icon. At the moment the leaf doesn't get any icon.

Thanks!

**Comment by martinpengellyphillips** [comment]
Thanks Lorenzo - I'll take a look at this in a bit, but it is low priority compared to the refactor and windows build issues. Feel free to submit a pull request if you have an approach you think will work.

**Comment by hdd** [comment]
Good point, 
there's a pull request available here : https://github.com/thesociable/dbootstrap/pull/30
