### ISSUE TITLE
dgrid style height of 100% makes it not render if outside of a parent container.

### ISSUE THREAD

**Issue by jaetea** [atoha/dbootstrap#73]
Go to any of the demo pages.

http://dojofoundation.org/packages/dgrid/tutorials/defining_grid_structures/demo/baseline.html

Change height to 100% in dev tools and grid doesn't render.

![image](https://f.cloud.github.com/assets/3731879/873662/ab6a9f32-f87c-11e2-83bb-1351f92b1b46.png)

**Comment by dylans** [comment]
That's usually the result of setting it to 100% of whatever contains it. If that container has no explicit height, then it would be interpreted as zero and so you would get 100% of 0. The solution is to set the height of the body and html elements to be 100%

**Comment by jaetea** [comment]
Should Grid.styl have 100% height explicitly set then? Or should it be something like height:auto?

**Comment by martinpengellyphillips** [comment]
It was originally set due to the expectation of a Grid being inside a ContentPane. However, it is probably better if users use the DijitRegistry mixin when adding the Grid to a layout, in which case it can be removed (and will default to the dgrid default of height: 30em).

**Comment by jaetea** [comment]
Thanks! We use dgrid inside any number of portlets, pages, modals, etc. It might not always be inside a content pane.

**Comment by martinpengellyphillips** [comment]
No problem and thanks for the report! Change is now merged to master.
