### ISSUE TITLE
Does dbootstrap support responsive apps?

### ISSUE THREAD

**Issue by pmlopes** [atoha/dbootstrap#79]
Bootstrap is built with the concept of responsive design, does dbootstrap also support it? is there a simple demo of the feature? I was trying to see it in action but cannot get it to work...

**Comment by martinpengellyphillips** [comment]
There is no specific support for the responsive design concept you are referring to at present. Some discussion regarding Dojo and responsive design in general can be found at http://dojo-toolkit.33424.n3.nabble.com/Responsive-design-and-Rem-in-dojo-td3985879.html

The dbootstrap demo uses Dojo layouts to handle sizing etc. As the discussion above suggests I guess there is some work that could be done to make this theme work with responsive design, but that is not currently an area I am looking into. More than happy to accept pull requests though ;-)

**Comment by pmlopes** [comment]
Thanks for your answer, I am not an expert on CSS and media queries so sorry I cannot provide any pull request now.
