### ISSUE TITLE
Build issue on Windows

### ISSUE THREAD

**Issue by rich-frost** [atoha/dbootstrap#80]
Hi,

Just cloned your repo, and tried running the build process, but have gotten the following error:

$ python build.py -v debug theme
INFO:dbootstrap.build:Building theme to c:\wamp\www\dbootstrap\build\theme
INFO:dbootstrap.build:Building CSS.
DEBUG:dbootstrap.build.execute:Running command: stylus.cmd --include c:\wamp\www\dbootstrap\source\nib\lib --include c:\wamp\www\dbootstrap\source\dbootstrap\theme\dbootstrap c:\wamp\www\dbootstrap\source\dbootstrap\theme\dbootstrap\index.styl
Traceback (most recent call last):
  File "build.py", line 308, in <module>
    raise SystemExit(main())
  File "build.py", line 66, in main
    os.path.join(dbootstrap_theme_path, 'index.styl')
  File "build.py", line 254, in execute
    str(error)
**main**.CommandExecutionException: stylus.cmd --include c:\wamp\www\dbootstrap\source\nib\lib --include c:\wamp\www\dbootstrap\source\dbootstrap\theme\dbootstrap c:\wamp\www\dbootstrap\source\dbootstrap\theme\dbootstrap\index.styl failed due to error: [Error 2] The system cannot find the file specified.

I've not really done much Python, had a bit of a play trying to fix it, and hardcoded the directories but can't get this to work. The file is definitely in the directory specified.

Appreciate any help

**Comment by martinpengellyphillips** [comment]
Python's error in this case is a little misleading, but means that Python could not find `stylus.cmd` for running in a subprocess.

How did you install Stylus?

**Comment by rich-frost** [comment]
Hmm ok that is strange, I thought it couldn't find index.styl. I used npm as suggested on their website: http://learnboost.github.io/stylus/

npm install stylus

**Comment by martinpengellyphillips** [comment]
Hmmm. Are you able to run `stylus.cmd` manually from the same terminal you are running the build?

**Comment by rich-frost** [comment]
Ok, my bad - stylus didn't seem to install when I ran that. Using this article http://bootstrap.pk/tutorials/getting-started-with-stylus-css-pre-processor/

I ran 'npm install stylus -g' and it seemed to install properly.

Cheers
