### ISSUE TITLE
Split the dbootstrap source out into its own repo.

### ISSUE THREAD

**Issue by DavidSpriggs** [atoha/dbootstrap#87]
Would it be possible to split out the source/dbootstrap dir into its own repo? This would allow the dbootstrap source to be added as a sub module to other projects (including this one). Also would be nice for the source to have releases that match the dojo releases.

**Comment by martinpengellyphillips** [comment]
Yep. Have been thinking about this and it wouldn't be too hard the way it is set up at the moment. Also been meaning to do a release tag.

**Comment by davewilton** [comment]
This would also allow bower delivery see https://github.com/atoha/dbootstrap/issues/91
