### ISSUE TITLE
Can't build on OSX

### ISSUE THREAD

**Issue by cjeriksson** [atoha/dbootstrap#88]
As far as I can tell I have all the right dependencies set up - but building fails with the following error:

localhost:dbootstrap johan$ python build.py demo
INFO:dbootstrap.build:Building demo to /Users/johan/dbootstrap/dbootstrap/build/demo
INFO:dbootstrap.build:Building CSS.
Traceback (most recent call last):
  File "build.py", line 308, in <module>
    raise SystemExit(main())
  File "build.py", line 66, in main
    os.path.join(dbootstrap_theme_path, 'index.styl')
  File "build.py", line 254, in execute
    str(error)
**main**.CommandExecutionException: stylus --include /Users/johan/dbootstrap/dbootstrap/source/nib/lib --include /Users/johan/dbootstrap/dbootstrap/source/dbootstrap/theme/dbootstrap /Users/johan/dbootstrap/dbootstrap/source/dbootstrap/theme/dbootstrap/index.styl failed due to error: [Errno 2] No such file or directory.

Am I doing something wrong ?

**Comment by martinpengellyphillips** [comment]
This error usually means that 'stylus' can not be found as a command to run. Are you able to run 'stylus' manually from a terminal?

**Comment by cjeriksson** [comment]
Ah, excellent - that did the trick. Stylus wasn't on the path. Thanks !

**Comment by CrypticArtsLaboratory** [comment]
I have the same issue although stylus is in my path I think my issuee was that I downloaded the following file from http://thesociable.github.io/dbootstrap/: thesociable-dbootstrap-dojo-1.8.5-25-g9d88eac.tar.gz (big blue download latest(dev)) button

It did not include all the files, namely missing, dijit dojo dojox nib put-selector util xstyle

using the clone of the repository fixed the issue
