### ISSUE TITLE
Editor not working

### ISSUE THREAD

**Issue by rjamesnw** [atoha/dbootstrap#9]
The editor is not showing any icons in chrome.

**Comment by martinpengellyphillips** [comment]
Thanks for the report. Haven't styled the editor yet so it is not working in any browser. Will leave this open as reminder.

**Comment by rjamesnw** [comment]
Ok.  Also great work thus far. ;)  Is DBootstrap  an actual “theme” that can be applied to  any existing Dojo/Dijit implementation, or would a lot of changes be required?

**Comment by martinpengellyphillips** [comment]
Cheers! It is implemented as an actual theme and the goal is to have it easy to switch to for an existing implementation.
