### ISSUE TITLE
Cannot build theme on linux

### ISSUE THREAD

**Issue by bosticka** [atoha/dbootstrap#90]
Hi,

My node build is failing with a "Error: This socket is closed." message.  I have seen one other ticket with this exact error on another project so possibly it is a dojo problem?  I am not a node user so any help is welcome.

See also https://github.com/kitsonk/dojo-node-boilerplate/issues/5 for this exact problem in a different dojo / node project.

Thanks,
Aaron

<pre>
bosticka@db ~/boot $ uname -a
Linux db.dandsltd.com 2.6.32-042stab076.8 #1 SMP Tue May 14 20:38:14 MSK 2013 x86_64 x86_64 x86_64 GNU/Linux
bosticka@db ~ $ python --version
Python 2.7.3
bosticka@db ~ $ node --version  
v0.10.21
bosticka@db ~ $ stylus --version  
0.38.0
bosticka@db ~ $ java -version  
java version "1.7.0_25"
OpenJDK Runtime Environment (rhel-2.3.10.5.el5_9-x86_64)
OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)
bosticka@db ~ $ mkdir boot
bosticka@db ~ $ cd boot
bosticka@db ~/boot $ git clone --recursive git://github.com/thesociable/dbootstrap.git
Cloning into 'dbootstrap'...

[ text cut out ]

bosticka@db ~/boot $ cd dbootstrap/
bosticka@db ~/boot/dbootstrap $ python build.py -v debug theme
INFO:dbootstrap.build:Building theme to /home/bosticka/boot/dbootstrap/build/theme
INFO:dbootstrap.build:Building CSS.
DEBUG:dbootstrap.build.execute:Running command: stylus --include /home/bosticka/boot/dbootstrap/source/nib/lib --include /home/bosticka/boot/dbootstrap/source/dbootstrap/theme/dbootstrap /home/bosticka/boot/dbootstrap/source/dbootstrap/theme/dbootstrap/index.styl
DEBUG:dbootstrap.build.execute:compiled /home/bosticka/boot/dbootstrap/source/dbootstrap/theme/dbootstrap/index.css
INFO:dbootstrap.build:Building Javascript packages.
DEBUG:dbootstrap.build.execute:Running command: node /home/bosticka/boot/dbootstrap/source/dojo/dojo.js load=build --profile /home/bosticka/boot/dbootstrap/resource/dbootstrap_profile.js --releaseDir /home/bosticka/boot/dbootstrap/build/theme
DEBUG:dbootstrap.build.execute:processing profile resource /home/bosticka/boot/dbootstrap/resource/dbootstrap_profile.js
DEBUG:dbootstrap.build.execute:info(107) Package Version: package: dojo; version: 1.9.1
DEBUG:dbootstrap.build.execute:processing profile resource /home/bosticka/boot/dbootstrap/source/dojo/dojo.profile.js
DEBUG:dbootstrap.build.execute:info(107) Package Version: package: dijit; version: 1.9.1
DEBUG:dbootstrap.build.execute:processing profile resource /home/bosticka/boot/dbootstrap/source/dijit/dijit.profile.js
DEBUG:dbootstrap.build.execute:info(107) Package Version: package: xstyle; version: 0.1.2
DEBUG:dbootstrap.build.execute:processing profile resource /home/bosticka/boot/dbootstrap/source/xstyle/package.js
DEBUG:dbootstrap.build.execute:processing profile resource /home/bosticka/boot/dbootstrap/source/dbootstrap/package.js
DEBUG:dbootstrap.build.execute:discovering resources...
DEBUG:dbootstrap.build.execute:starting reading resources...
DEBUG:dbootstrap.build.execute:starting processing raw resource content...
DEBUG:dbootstrap.build.execute:starting tokenizing resource...
DEBUG:dbootstrap.build.execute:starting processing resource tokens...
DEBUG:dbootstrap.build.execute:starting parsing resource...
DEBUG:dbootstrap.build.execute:starting processing resource AST...
DEBUG:dbootstrap.build.execute:warn(216) dojo/has plugin resource could not be resolved during build-time. plugin resource id: dojo-firebug?./_firebug/firebug; reference module id: dojo/main
DEBUG:dbootstrap.build.execute:warn(216) dojo/has plugin resource could not be resolved during build-time. plugin resource id: dom-addeventlistener?:./aspect; reference module id: dojo/on
DEBUG:dbootstrap.build.execute:warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dojo/request; plugin: dojo/request/default
DEBUG:dbootstrap.build.execute:warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dojo/request/node; plugin: dojo/node
DEBUG:dbootstrap.build.execute:warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dojo/request/node; plugin: dojo/node
DEBUG:dbootstrap.build.execute:warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dojo/request/node; plugin: dojo/node
DEBUG:dbootstrap.build.execute:warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dojo/request/node; plugin: dojo/node
DEBUG:dbootstrap.build.execute:warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dojo/request/registry; plugin: dojo/request/default
DEBUG:dbootstrap.build.execute:warn(216) dojo/has plugin resource could not be resolved during build-time. plugin resource id: host-browser?dom-addeventlistener?:../on:; reference module id: dojo/request/watch
DEBUG:dbootstrap.build.execute:warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dijit/Fieldset; plugin: dojo/query
DEBUG:dbootstrap.build.execute:warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dijit/Tree; plugin: dojo/query
DEBUG:dbootstrap.build.execute:warn(216) dojo/has plugin resource could not be resolved during build-time. plugin resource id: dojo-bidi?./_BidiMixin; reference module id: dijit/_WidgetBase
DEBUG:dbootstrap.build.execute:error(311) Missing dependency. module: xstyle/main; dependency: put-selector/put
DEBUG:dbootstrap.build.execute:warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dbootstrap/main; plugin: xstyle/css
DEBUG:dbootstrap.build.execute:starting executing global optimizations...
DEBUG:dbootstrap.build.execute:starting writing resources...
DEBUG:dbootstrap.build.execute:[Error: This socket is closed.]
DEBUG:dbootstrap.build.execute:Error: This socket is closed.
DEBUG:dbootstrap.build.execute:at Socket._write (net.js:635:19)
DEBUG:dbootstrap.build.execute:at doWrite (_stream_writable.js:221:10)
DEBUG:dbootstrap.build.execute:at writeOrBuffer (_stream_writable.js:211:5)
DEBUG:dbootstrap.build.execute:at Socket.Writable.write (_stream_writable.js:180:11)
DEBUG:dbootstrap.build.execute:at Socket.write (net.js:613:40)
DEBUG:dbootstrap.build.execute:at Object.proc.write (/home/bosticka/boot/dbootstrap/source/util/build/transforms/optimizer/sendJob.js:95:20)
DEBUG:dbootstrap.build.execute:at sendJob (/home/bosticka/boot/dbootstrap/source/util/build/transforms/optimizer/sendJob.js:37:28)
DEBUG:dbootstrap.build.execute:at /home/bosticka/boot/dbootstrap/source/util/build/transforms/optimizer/closure.js:18:7
DEBUG:dbootstrap.build.execute:at /home/bosticka/boot/dbootstrap/source/util/build/node/fs.js:23:9
DEBUG:dbootstrap.build.execute:at Object.oncomplete (fs.js:107:15)
WARNING:dbootstrap.build.execute:Command node /home/bosticka/boot/dbootstrap/source/dojo/dojo.js load=build --profile /home/bosticka/boot/dbootstrap/resource/dbootstrap_profile.js --releaseDir /home/bosticka/boot/dbootstrap/build/theme exited with code 255
INFO:dbootstrap.build:Removing temporary and unnecessary files.
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/source/dbootstrap/theme/dbootstrap/dbootstrap.css
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dojo
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dijit
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/xstyle
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/layout/ContentPane.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/layout/index.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/layout/TabContainer.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/layout/AccordionContainer.styl
DEBUG:dbootstrap.build:Removing empty directory /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/layout
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/form/index.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/form/Button.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/form/Slider.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/form/Select.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/form/Common.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/form/RadioButton.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/form/NumberSpinner.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/form/Checkbox.styl
DEBUG:dbootstrap.build:Removing empty directory /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/form
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/icon.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/index.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/Menu.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/Common.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/scaffolding.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/alert.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/Grid.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/ProgressBar.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/TitlePane.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/Calendar.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/well.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/Dialog.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/type.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/Editor.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/variables.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/Toolbar.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/mixins.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/Application.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/Tree.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/font_awesome.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/theme/dbootstrap/TimePicker.styl
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/icon_support.js.uncompressed.js
DEBUG:dbootstrap.build:Removing /home/bosticka/boot/dbootstrap/build/theme/dbootstrap/main.js.uncompressed.js
INFO:dbootstrap.build:Build completed with issues.
<pre>

**Comment by martinpengellyphillips** [comment]
Hey, sorry for delayed response. Haven't had time to look at dbootstrap recently.

Did you find a solution to this?

**Comment by bosticka** [comment]
Sorry I haven't.  I am currently just using a prebuilt version you made available for download.

How hard is it to build against version 1.8.5 of dojo?  I had some trouble with the 1.9 line and reverted.

**Comment by martinpengellyphillips** [comment]
Should be fine to build against Dojo 1.8.5 (just change the submodule checkout tag in your local copy).

**Comment by bosticka** [comment]
Using version 1.8.5 or version 1.9.1 or HEAD does not matter, though I am getting a different error now.  The node build command is now saying:

<pre>node /usr/share/nginx/dragon-dev/test/dbootstrap/source/dojo/dojo.js load=build --profile /usr/share/nginx/dragon-dev/test/dbootstrap/resource/dbootstrap_profile.js --releaseDir /usr/share/nginx/dragon-dev/test/dbootstrap/build/theme
processing profile resource /usr/share/nginx/dragon-dev/test/dbootstrap/resource/dbootstrap_profile.js
info(107) Package Version: package: dojo; version: 1.8.5
processing profile resource /usr/share/nginx/dragon-dev/test/dbootstrap/source/dojo/dojo.profile.js
info(107) Package Version: package: dijit; version: 1.8.5
processing profile resource /usr/share/nginx/dragon-dev/test/dbootstrap/source/dijit/dijit.profile.js
info(107) Package Version: package: xstyle; version: 0.1.4
processing profile resource /usr/share/nginx/dragon-dev/test/dbootstrap/source/xstyle/package.js
processing profile resource /usr/share/nginx/dragon-dev/test/dbootstrap/source/dbootstrap/package.js
discovering resources...
starting reading resources...
starting processing raw resource content...
starting tokenizing resource...
starting processing resource tokens...
starting parsing resource...
starting processing resource AST...
warn(216) dojo/has plugin resource could not be resolved during build-time. plugin resource id: dojo-firebug?./_firebug/firebug; reference module id: dojo/main
warn(216) dojo/has plugin resource could not be resolved during build-time. plugin resource id: dom-addeventlistener?:./aspect; reference module id: dojo/on
warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dojo/request; plugin: dojo/request/default
warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dojo/request/node; plugin: dojo/node
warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dojo/request/node; plugin: dojo/node
warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dojo/request/node; plugin: dojo/node
warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dojo/request/node; plugin: dojo/node
warn(224) A plugin dependency was encountered but there was no build-time plugin resolver. module: dojo/request/registry; plugin: dojo/request/default
warn(216) dojo/has plugin resource could not be resolved during build-time. plugin resource id: host-browser?dom-addeventlistener?:../on:; reference module id: dojo/request/watch
error(311) Missing dependency. module: dbootstrap/main; dependency: xstyle/css!./theme/dbootstrap/dbootstrap.css
starting executing global optimizations...
starting writing resources...
error(303) Missing include module for layer. missing: xstyle/load-css; layer: dbootstrap/main
[Error: This socket is closed.]
Error: This socket is closed.
    at Socket._write (net.js:635:19)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at Socket.Writable.write (_stream_writable.js:180:11)
    at Socket.write (net.js:613:40)
    at Object.proc.write (/usr/share/nginx/dragon-dev/test/dbootstrap/source/util/build/transforms/writeOptimized.js:224:21)
    at sendJob (/usr/share/nginx/dragon-dev/test/dbootstrap/source/util/build/transforms/writeOptimized.js:165:29)
    at /usr/share/nginx/dragon-dev/test/dbootstrap/source/util/build/transforms/writeOptimized.js:307:7
    at /usr/share/nginx/dragon-dev/test/dbootstrap/source/util/build/node/fs.js:23:9
    at Object.oncomplete (fs.js:107:15)
</pre>

Can you replicate?

**Comment by pixelheresy** [comment]
I get a similar issue, but not the same on Linux... It merely chokes when trying to build. I did try rolling back to 1.8.5 (not just in `/source/dojo` but in `dijit`, `dojox`, and `util`). Still nothing. 

```
WARNING:dbootstrap.build.execute:Command node /home/apsuser/projects/dbootstrap/source/dojo/dojo.js load=build --profile /home/apsuser/projects/dbootstrap/resource/dbootstrap_profile.js --releaseDir /home/apsuser/projects/dbootstrap/build/theme exited with code 1
```

Any clue what is up? Both `node.js` and `python` are appropriate versions.

**Comment by bosticka** [comment]
Run the node build command by itself like:

node /home/apsuser/projects/dbootstrap/source/dojo/dojo.js load=build
--profile /home/apsuser/projects/dbootstrap/resource/dbootstrap_profile.js
--releaseDir /home/apsuser/projects/dbootstrap/build/theme

and you should see an error message with more information than just
"code 1".  I still have no gotten it to build myself.

Aaron

**Comment by bosticka** [comment]
So I finally got this to build because I was seeing the same error in my own project build.  Come to find out, it has to do with the build setting "maxOptimizationProcesses" which I believe determines how many layers to compile/optimize in parallel based on how many processors you have.

I have a 16 core (two 8 core xeon cpus) server but run my builds inside my OpenVZ container on Centos 5.9.  Something about my setup will not let me run maxOptimizationProcesses higher than 2.  The moment I set it to 3 or more, it fails.

On the dojo side, you can use java to run the closure compiler and java works fine.  It is only node that has the issue.  Since dbootstrap's build.py only uses node, I was running into this.  

My "fix" was to set maxOptimizationProcesses to 2 in the file:
./dbootstrap/source/util/build/buildControlBase.js

I can only assume this is a OpenVZ related issue because I have tried multiple versions of node and java...

 Hope this helps someone else cause this took me a while to figure out! :)
