### ISSUE TITLE
icon_support does not patch dijit/_AttachMixin in Dojo 1.9+

### ISSUE THREAD

**Issue by edhager** [atoha/dbootstrap#93]
`dbootstrap/icon_support` is using the following check to determine if `dijit/_AttachMixin` or `dijit/_TemplatedMixin` should be patched:

``` js
if (TemplatedMixin.prototype._attachTemplateNodes === undefined) {
    // patch dijit/_AttachMixin
} else {
    // patch dijit/_TemplatedMixin
}
```

The problem is that `TemplatedMixin.prototype._attachTemplateNodes` is never undefined.  `_TemplatedMixin` has `_AttachMixin` mixed into its prototype in Dojo 1.9.  Here is code that will show that `_TemplatedMixin` is being patched and `_AttachMixin` is not:

``` js
require([
    "dbootstrap",
    "dijit/_AttachMixin",
    "dijit/_TemplatedMixin"

], function (dbootstrap, AttachMixin, TemplatedMixin) {
    console.log("AttachMixin.prototype._attachTemplateNodes:", AttachMixin.prototype._attachTemplateNodes);
    console.log("TemplatedMixin.prototype._attachTemplateNodes:", TemplatedMixin.prototype._attachTemplateNodes);
});
```

**Comment by martinpengellyphillips** [comment]
Hmmm. It worked when we addressed this in #48 ( #54, #58 ) I believe, but maybe something has changed in Dojo since then. 

Anyway, thanks for the report - any thoughts on an appropriate solution?

**Comment by edhager** [comment]
I have an update that I am testing:
https://github.com/edhager/dbootstrap/compare/patch-AttachMixin

Hopefully I will have a pull request soon.

**Comment by edhager** [comment]
For reference, here is the pull request: https://github.com/thesociable/dbootstrap/pull/94

**Comment by martinpengellyphillips** [comment]
Pull request merged.
