### ISSUE TITLE
Building issues

### ISSUE THREAD

**Issue by TomasLudvik** [atoha/dbootstrap#96]
Hi there,

I've read allmost every issue here and I have a question. Almost everybody has some issues with building files or getting them to work. Not everybody using js + css is used to build files, install so many dependencies from repositories etc.

Could you create builded version for us noobs add there some fast installation steps and public it here on github? It would save a lot of time and problems for dummies like me.

Thanks

**Comment by nicolasiac** [comment]
I need this as well. The theme is awesome but I don't have the knowledge of doing the build myself

**Comment by martinpengellyphillips** [comment]
Good call. I had planned to do this, but haven't had time recently to spend on this project. Hope to change that soon. Also, I think github have made it easier to include built versions now in the release.

**Comment by KateHodge** [comment]
Seconded (or thirded!).  @thesociable : this looks excellent.  I'd really like to use it but I can't get it to build either (I'm getting the same problem with stylus.cmd others have reported).  A compiled version we can just include on a website and reference would be brilliant.  It's a great looking theme - much preferred to claro.  I really hope you can find some time!

**Comment by martinpengellyphillips** [comment]
Uploaded a copy of the theme under https://github.com/thesociable/dbootstrap/releases

Let me know if it works for you.
