### ISSUE TITLE
Windows Build error - missing file

### ISSUE THREAD

**Issue by tchapin** [atoha/dbootstrap#99]
Having a problem building in Windows.  I installed Node.js and stylus.  Here's the message:

C:\dbootstrap-master>stylus --version
0.43.1

C:\dbootstrap-master>python build.py theme
INFO:dbootstrap.build:Building theme to C:\dbootstrap-master\build\theme
INFO:dbootstrap.build:Building CSS.
WARNING:dbootstrap.build.execute:Command stylus.cmd --include C:\dbootstrap-master\source\nib\lib --include C:\dbootstrap-master\source\dbootstrap\theme\dbootstrap C:\dbootstrap-master\source\dbootstr
ap\theme\dbootstrap\index.styl exited with code 8
Traceback (most recent call last):
  File "build.py", line 308, in <module>
    raise SystemExit(main())
  File "build.py", line 77, in main
    dbootstrap_css_path
WindowsError: [Error 2] The system cannot find the file specified

NOTE: c:\dbootstrap-master\source\nib folder is empty, lib does not exist.

**Comment by tchapin** [comment]
C:\dbootstrap-master>python build.py -v debug theme
INFO:dbootstrap.build:Building theme to C:\dbootstrap-master\build\theme
INFO:dbootstrap.build:Building CSS.
DEBUG:dbootstrap.build.execute:Running command: stylus.cmd --include C:\dbootstrap-master\source\nib\lib --include C:\dbootstrap-master\source\dbootstrap\theme\dbootstrap C:\dbootstrap-master\source\d
bootstrap\theme\dbootstrap\index.styl
DEBUG:dbootstrap.build.execute:C:\Users\tchapin\AppData\Roaming\npm\node_modules\stylus\bin\stylus:595
DEBUG:dbootstrap.build.execute:throw err;
DEBUG:dbootstrap.build.execute:^
DEBUG:dbootstrap.build.execute:Error: C:\dbootstrap-master\source\dbootstrap\theme\dbootstrap\index.styl:5
DEBUG:dbootstrap.build.execute:1| // :copyright: Copyright 2012 Martin Pengelly-Phillips
DEBUG:dbootstrap.build.execute:2| // :license: See LICENSE.txt.
DEBUG:dbootstrap.build.execute:3|
DEBUG:dbootstrap.build.execute:4| // From Nib
DEBUG:dbootstrap.build.execute:> 5| @import 'nib';
DEBUG:dbootstrap.build.execute:6| global_reset();
DEBUG:dbootstrap.build.execute:7|
DEBUG:dbootstrap.build.execute:8| // From Dojo
DEBUG:dbootstrap.build.execute:failed to locate @import file nib.styl
DEBUG:dbootstrap.build.execute:at Evaluator.visitImport (C:\Users\tchapin\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:877:21)
DEBUG:dbootstrap.build.execute:at Evaluator.Visitor.visit (C:\Users\tchapin\AppData\Roaming\npm\node_modules\stylus\lib\visitor\index.js:28:40)
DEBUG:dbootstrap.build.execute:at Evaluator.visit (C:\Users\tchapin\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:157:18)
DEBUG:dbootstrap.build.execute:at Evaluator.visitRoot (C:\Users\tchapin\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:706:27)
DEBUG:dbootstrap.build.execute:at Evaluator.Visitor.visit (C:\Users\tchapin\AppData\Roaming\npm\node_modules\stylus\lib\visitor\index.js:28:40)
DEBUG:dbootstrap.build.execute:at Evaluator.visit (C:\Users\tchapin\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:157:18)
DEBUG:dbootstrap.build.execute:at Evaluator.evaluate (C:\Users\tchapin\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:232:15)
DEBUG:dbootstrap.build.execute:at Renderer.render (C:\Users\tchapin\AppData\Roaming\npm\node_modules\stylus\lib\renderer.js:80:26)
DEBUG:dbootstrap.build.execute:at C:\Users\tchapin\AppData\Roaming\npm\node_modules\stylus\bin\stylus:589:15
DEBUG:dbootstrap.build.execute:at fs.js:266:14
WARNING:dbootstrap.build.execute:Command stylus.cmd --include C:\dbootstrap-master\source\nib\lib --include C:\dbootstrap-master\source\dbootstrap\theme\dbootstrap C:\dbootstrap-master\source\dbootstr
ap\theme\dbootstrap\index.styl exited with code 8
Traceback (most recent call last):
  File "build.py", line 308, in <module>
    raise SystemExit(main())
  File "build.py", line 77, in main
    dbootstrap_css_path
WindowsError: [Error 2] The system cannot find the file specified

**Comment by KateHodge** [comment]
I'm having the same problem.  Did you manage to get it working?

**Comment by tchapin** [comment]
No, I never did get it working.

**Comment by iToreTS** [comment]
Have you seen this?
http://stackoverflow.com/questions/14815346/dojo-twitter-bootstrap-and-dijits/14833126

There are actually two different links to  zip-files that should contain a pre-built version in this Stackoverflow thread.

**Comment by KateHodge** [comment]
@iToreTS that looks very useful - thanks very much for sharing it.

**Comment by martinpengellyphillips** [comment]
Have uploaded a new copy of the built theme under releases (https://github.com/thesociable/dbootstrap/releases). 

Regarding the error you saw - had you cloned the dbootstrap repository with `--recursive` in order to also pull in the submodules (nib and others)?

**Comment by tchapin** [comment]
I didn't clone it, I just downloaded the master.zip.  But not sure I need to if the built release works?

**Comment by KateHodge** [comment]
@thesociable thanks for creating the prebuilt version.  I've switched over to it from the one linked from StackOverflow and it's working well.

**Comment by martinpengellyphillips** [comment]
@tchapin You shouldn't need it if you just want to use the prebuilt theme. However, if you do want to modify the source you should git clone with recursive option rather than downloading the zip file as otherwise you will have to also download and install all the other dependencies.

@sbhodge80 Good to hear - thanks for reporting back.
